version: '3.8'

services:
  db:
    container_name: henhouse_db
    image: postgres:latest
    environment:
      POSTGRES_USER: henhouse
      POSTGRES_PASSWORD: henhouse
      POSTGRES_DB: henhouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U henhouse"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
